---
- import_tasks: config.yml

- import_tasks: start.yml
  when: postgres_ha_is_master

- import_tasks: hba.yml
  when: postgres_ha_is_master

- import_tasks: users.yml
  when: postgres_ha_is_master and postgres_ha_replica_enabled

- import_tasks: replica.yml
  when: not postgres_ha_is_master

- import_tasks: start.yml
  when: not postgres_ha_is_master

- import_tasks: consul.yml

- import_tasks: backup.yml
  when: postgres_ha_backup
